language: java
jdk:
    - openjdk11
addons:
  ssh_known_hosts: 
    - 23.97.183.10
    - 51.136.6.40

env:
    - NODE_VERSION="v12.18.0"
      
before_install:
    - nvm install $NODE_VERSION
    - node --version
    - npm --version
    - sudo apt-get update -y
    - sudo apt-get install -y expect

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
    npm: true

script:
    - if [[ $TRAVIS_EVENT_TYPE == "pull_request" && ($TRAVIS_PULL_REQUEST_BRANCH == "dev") ]]  then bash scripts/test.sh  fi
    - if [[ $TRAVIS_EVENT_TYPE == "push"]] then\
        if [[ $TRAVIS_BRANCH == "dev" ]]\
            then bash scripts/build.sh && expect scripts/deploy.sh\
        else\
            bash scripts/test.sh \
        fi\ 
        fi

notifications:
  slack:
    on_success: never
    on_failure: always
    secure: BrVZi8P29lTEQY2+4Sval7o+3bunrQ8dyxzuPClpjd2ZBmng7e4uYhU0f+SrzJaif9jZYL1geXiQj4nTsycGzab2eTEn/c3RGTgnxn1v0pdc/bxw/oiADfephPurwbjhkcMgKocpYeg/P305DrzRbVzFvyX2lGwyLGkI1NNVKkbfAAWPzdeF9IY4gpLYLurEySa6EVkFUfVJdm9J8WEQ8WOJvzHkEGyqmDWs3nrtf3gD2Gl9fUtvGDKGbaVovumuAplAWh0warYrl9XNiKQNwNRLbSyHQJc9jlTx/1KP1NpuNcwVy20nVL7TQrf6N1PRuV9BeOR0/bxvpjKjaV1ovHABdYp/0pzYj5yovUdsz8EV1TYRW8O/eaxz6VSaQC/XDdTlxmk62HTs6Jqj0s87N125PKR1ytDtii2YgT4iWyCOr+rq61XalDvofNDqdWJD1XhhyU5DrQ+2h0g/5F6CMjwRqYMuIXyUlupg+Mu11hReI98QGcOnhH3nJwtIFcmF8wEj3U5eZm0z2yq8RKxqABB/qL4F5kxJX+ytOWBUF+S4MZMmgX4+E8zqoXxE6jjGUy/PIEpAHmyNvlUln2Npi/rgqLzJtuPIE7piVanKkPDDWzhrkDe+Ym0FUc3/orN9K/rqxkpylKN3TsYdQqdRLQu7v8+3Vx3IE8Vb6otPoE8=
