export const SET_USER = 'SIGN_IN_ACTION:SET_USER';
export const LOGIN = 'SIGN_IN:LOGIN';
export const SET_VALIDATION_ERRORS = 'SIGN_IN:SET_VALIDATION_ERRORS';
export const SET_IS_LOADING = 'SIGN_IN:SET_IS_LOADING';
export const SET_VALIDATION_ERRORS_SUCCESS = 'SIGN_IN:SET_VALIDATION_ERRORS_SUCCESS';

